// document.querySelector('[data-text]').style.color = '#f22';
// document.querySelector('h1').style.backgroundColor = '#f99'

// const h4 = document.createElement('h4')
// h4.innerHTML = 'some random text';
// h4.classList = 'random'
// h4.setAttribute('id','js-h4')
// h4.style.fontSize = '3em'
// h4.style.setProperty('border', '2px solid')
// h4.style.setProperty('text-transform', 'uppercase')
// document.body.appendChild(h4)

// let image = document.createElement('img')
// let figure = document.querySelector('figure')
// // image.setAttribute('src', 'https://picsum.photos/id/1070/300')
// image.src = 'https://picsum.photos/id/1071/300'
// image.setAttribute('alt','this image was generated by js')
// image.width = 600
// figure.appendChild(image)

// const article = document.querySelector('.wrapper')
// const p = document.createElement('p')
// p.textContent = 'hello world'
// article.appendChild(p)